name: CI

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set extension directory name
              id: vars
              run: | 
                # Read UUID from metadata.json
                EXT_UUID=$(jq -r '.uuid' metadata.json)
                printf 'uuid=%s\n' "$EXT_UUID" >> "$GITHUB_OUTPUT"

            - name: Debug UUID
              run: | 
                echo "UUID is: ${{ steps.vars.outputs.uuid }}"

            - name: Prepare extension directory
              run: |
                mkdir -p build/${{ steps.vars.outputs.uuid }}
                cp -r * build/${{ steps.vars.outputs.uuid }}/
                rm -rf build/${{ steps.vars.outputs.uuid }}/commands.txt
                rm -rf build/${{ steps.vars.outputs.uuid }}/dist
                rm -rf build/${{ steps.vars.outputs.uuid }}/.git
                rm -rf build/${{ steps.vars.outputs.uuid }}/.github

            - name: Create ZIP
              run: | 
                mkdir -p dist
                zip -r "dist/${{ steps.vars.outputs.uuid }}.zip" "build/${{ steps.vars.outputs.uuid }}"

            - name: Create Github release
              uses: softprops/action-gh-release@v2
              with:
                files: dist/*.zip
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}